version: "3.3"
services:
  user-database:
    image: postgres:10.5
    ports:
      - "5433:5432"
    env_file: database-variables.env
    volumes:
      - data-volume:/var/lib/postgresql/user-data

  liquibase-practice:
    image: liquibase-practice
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=docker

volumes:
  data-volume: